### ISSUE TITLE
Broken on Logseq 0.7.2 (Windows)?

### ISSUE THREAD

**Issue by asifm** [hyrijk/logseq-plugin-split-block#4]
Suddenly stopped working. Most likely after I installed the new version of Logseq (0.7.2). But I'm not sure.

This is what gets printed on the console when I trigger the "split block" command.

```
index.4a80dd6f.js:1 [{"content":"test block line 1","children":[]},{"content":"line 2","children":[]},{"content":"line 3","children":[]}]

lsplugin.core.js:2 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': function() {
    var $r$jscomp$23_temp__5720__auto__$jscomp$7$$ = $APP.$cljs$core$seq$$($coll$jscomp$330$$);
  ...<omitted>... } could not be cloned.
    at Bt.call (file:///C:/ProgramData/.../Logseq/app-0.7.2/resources/app/js/lsplugin.core.js:2:58696)
    at wn._callUserModel (file:///C:/ProgramData/.../Logseq/app-0.7.2/resources/app/js/lsplugin.core.js:2:74438)
    at wn.callUserModel (file:///C:/ProgramData/.../Logseq/app-0.7.2/resources/app/js/lsplugin.core.js:2:73124)
    at e (file:///C:/ProgramData/.../Logseq/app-0.7.2/resources/app/js/lsplugin.core.js:2:79361)
call @ lsplugin.core.js:2
_callUserModel @ lsplugin.core.js:2
callUserModel @ lsplugin.core.js:2
e @ lsplugin.core.js:2
```

**Comment by asifm** [comment]
Working again after installing Logseq 0.7.3 (Windows). So, closing the issue.
